# Checks that are run on every commit to main and every pull request.
name: Checks

on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  check_package:
    name: Using Flutter ${{ matrix.flutter-channel }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, macos, ubuntu]
        flutter-channel: [stable, beta]
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Flutter
        uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 # v2.16.0
        with:
          channel: ${{ matrix.flutter-channel }}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Get packages
        run: flutter pub get

      - name: Analyze Dart code
        run: flutter analyze

      - name: Ensure Dart code is formatted correctly
        run: dart format --set-exit-if-changed .

      - name: Run Flutter unit tests
        run: flutter test

      - name: Build example (windows)
        if: ${{ matrix.os == 'windows' }}
        working-directory: example
        run: flutter build windows --debug

      - name: Build example (linux)
        if: ${{ matrix.os == 'ubuntu' }}
        working-directory: example
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          flutter build linux --debug

      - name: Build example (macos)
        if: ${{ matrix.os == 'macos' }}
        working-directory: example
        run: flutter build macos --debug

      - name: Build example (android)
        working-directory: example
        run: flutter build apk --debug

      - name: Build example (ios)
        working-directory: example
        run: flutter build ipa --debug

      - name: Build example (web)
        working-directory: example
        run: flutter build web --debug
